#!/bin/sh
/usr/sbin/semanage boolean -m domain_can_mmap_files   -0
/usr/sbin/semanage boolean -m use_virtualbox          -0
#/usr/sbin/semanage boolean -m unconfined_login        -0
/usr/sbin/semanage boolean -m deny_bluetooth          -1
#/usr/sbin/semanage boolean -m deny_execmem            -0
/usr/sbin/semanage boolean -m deny_ptrace             -1
/usr/sbin/semanage boolean -m nis_enabled             -1
/usr/sbin/semanage boolean -m secure_mode             -1
/usr/sbin/semanage boolean -m selinuxuser_execstack   -0
/usr/sbin/semanage boolean -m virt_use_xserver        -1
